name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/_test.yml
